version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cooperfilme
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./roteiros
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cooperfilme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=OSz9pN0lkQm/nKVuvymYweQfLTluBODu9p5/jgMsDvg=
      - JWT_EXPIRATION=86400000
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: